apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: openhab_db
    user: openhab_ro
    password: 123456789
    url: http://influxdb:8086
    isDefault: true
    editable: true